name: Docker Image CD

on:
  push:
    branches: [ "master" ]
    
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name : Check out the code base
    - uses: actions/checkout@v4
    
    - name: Build the Docker image
      run: docker build .  -t vinay97kumar/continuous_php_image
